src/Entity/CategorieProduit.php
<?php

namespace App\Entity;

use App\Repository\CategorieProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieProduitRepository::class)
 */
class CategorieProduit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LibelleCat;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="categorieproduit")
     */
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelleCat(): ?string
    {
        return $this->LibelleCat;
    }

    public function setLibelleCat(string $LibelleCat): self
    {
        $this->LibelleCat = $LibelleCat;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setCategorieproduit($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategorieproduit() === $this) {
                $produit->setCategorieproduit(null);
            }
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomProduit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Caracteristiques;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=CategorieProduit::class, inversedBy="produits")
     */
    private $categorieproduit;

    

    public function __construct()
    {
        $this->ligneAchats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nomProduit;
    }

    public function setNomProduit(string $nomProduit): self
    {
        $this->nomProduit = $nomProduit;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getCaracteristiques(): ?string
    {
        return $this->Caracteristiques;
    }

    public function setCaracteristiques(string $Caracteristiques): self
    {
        $this->Caracteristiques = $Caracteristiques;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorieproduit(): ?CategorieProduit
    {
        return $this->categorieproduit;
    }

    public function setCategorieproduit(?CategorieProduit $categorieproduit): self
    {
        $this->categorieproduit = $categorieproduit;

        return $this;
    }

    
}

templates/pages/ProduitDetails.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CAGESI Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('boutique/css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/elegant-icons.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/nice-select.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/jquery-ui.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/style.css')}}" type="text/css">
	
</head>

<body>
    {{ include('components/boutiqueHeader.html.twig') }}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>CAGESI Shop</h2>
                        <div class="breadcrumb__option">
                            <span>details</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Details Section Begin -->
    <section class="product-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__pic">
                        <div class="product__details__pic__item">
                            <img class="product__details__pic__item--large"
                                src=" {{produit.image}} " alt="{{produit.image}}">
                        </div>
                        <div class="product__details__pic__slider owl-carousel">
                            <img data-imgbigurl="img/product/details/product-details-2.jpg"
                                src="img/product/details/thumb-1.jpg" alt="">
                            <img data-imgbigurl="img/product/details/product-details-3.jpg"
                                src="img/product/details/thumb-2.jpg" alt="">
                            <img data-imgbigurl="img/product/details/product-details-5.jpg"
                                src="img/product/details/thumb-3.jpg" alt="">
                            <img data-imgbigurl="img/product/details/product-details-4.jpg"
                                src="img/product/details/thumb-4.jpg" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__text">
                        <h3>{{produit.nomProduit}}</h3>
                        <span>{{produit.categorieproduit.libelleCat}}</span>
                        <div class="product__details__rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                            <span>(18 reviews)</span>
                        </div>
                        <form action="{{ path('panier_add',{'id': produit.id }) }}" method="POST">
                            <div class="product__details__price">{{produit.prix}} fcfa</div>
                            <p>{{produit.Caracteristiques}}.</p>
                            <div class="product__details__quantity">
                                <div class="quantity">
                                    <div class="pro-qty">
                                        <input type="text" name="quantite">
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary">Ajouter au panier</button>
                            <a href="#" class="heart-icon"><span class="icon_heart_alt"></span></a>
                        </form>
                        <ul>
                            <li><b>Disponible</b> <span>oui</span></li>
                            <li><b>partager sur</b>
                                <div class="share">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-instagram"></i></a>
                                    <a href="#"><i class="fa fa-pinterest"></i></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Details Section End -->

    <!-- Produits liste -->
    {{ include('components/DetailsProduits.html.twig') }}

    <!-- footer -->
    {{ include('components/boutiqueFooter.html.twig') }}

    <!-- Js Plugins -->
    <script src="{{asset('boutique/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{asset('boutique/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.nice-select.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery-ui.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.slicknav.js')}}"></script>
    <script src="{{asset('boutique/js/mixitup.min.js')}}"></script>
    <script src="{{asset('boutique/js/owl.carousel.min.js')}}"></script>
    <script src="{{asset('boutique/js/main.js')}}"></script>

</body>

</html>

templates/pages/ProduitParCategorie.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CAGESI Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('boutique/css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/elegant-icons.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/nice-select.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/jquery-ui.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/style.css')}}" type="text/css">
	
</head>

<body>
    {{ include('components/boutiqueHeader.html.twig') }}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>CAGESI Shop</h2>
                        <div class="breadcrumb__option">
                            <span>Produits</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Produits liste -->
    {{ include('components/ProduitCategorie.html.twig') }} 

    <!-- footer -->
    {{ include('components/boutiqueFooter.html.twig') }}

    <!-- Js Plugins -->
    <script src="{{asset('boutique/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{asset('boutique/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.nice-select.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery-ui.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.slicknav.js')}}"></script>
    <script src="{{asset('boutique/js/mixitup.min.js')}}"></script>
    <script src="{{asset('boutique/js/owl.carousel.min.js')}}"></script>
    <script src="{{asset('boutique/js/main.js')}}"></script>

</body>

</html>

templates/pages/Reglement.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CAGESI Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('boutique/css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/elegant-icons.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/nice-select.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/jquery-ui.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/style.css')}}" type="text/css">
	
    
</head>

<body>

    {{ include('components/boutiqueHeader.html.twig') }}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>CAGESI Shop</h2>
                        <div class="breadcrumb__option">
                            <span>Paiement</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    {{ include('components/ReglementPanier.html.twig') }}
	
    <!-- footer -->
	{{ include('components/boutiqueFooter.html.twig') }}
    

    <!-- Js Plugins -->
    <script src="{{asset('boutique/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{asset('boutique/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.nice-select.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery-ui.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.slicknav.js')}}"></script>
    <script src="{{asset('boutique/js/mixitup.min.js')}}"></script>
    <script src="{{asset('boutique/js/owl.carousel.min.js')}}"></script>
    <script src="{{asset('boutique/js/main.js')}}"></script>



</body>

</html>

templates/pages/accueil.html.twig
{% extends 'bases/base.html.twig'  %}

{% block body %}
{{ include('components/menu.html.twig') }}
{% block header %}
    <div class="hero_slider_container">
        <div class="hero_slider owl-carousel">

            <!-- Hero Slide -->
            <div class="hero_slide">
                <div class="hero_slide_background" style="background-image:url(images/neutre.jpg)"></div>
                <div class="hero_slide_container d-flex flex-column align-items-center justify-content-center">

                    <div class="hero_slide_content text-center">
                        <h1 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOut"><span>{% trans %}SYSTEMES INFORMATIQUES{% endtrans %}</span> </h1>
                    </div>
                </div>
            </div>

            <!-- Hero Slide -->
            <div class="hero_slide">
                <div class="hero_slide_background" style="background-image:url(images/code.jpg)"></div>
                <div class="hero_slide_container d-flex flex-column align-items-center justify-content-center">
                    <div class="hero_slide_content text-center">
                        <h1 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOut"><span>{% trans %}NOUVELLES TECHNOLOGIES{% endtrans %}</span> </h1>
                    </div>
                </div>
            </div>

            <!-- Hero Slide -->
            <div class="hero_slide">
                <div class="hero_slide_background" style="background-image:url(images/solutionLigne.jpg)"></div>
                <div class="hero_slide_container d-flex flex-column align-items-center justify-content-center">
                    <div class="hero_slide_content text-center">
                        <h1 data-animation-in="fadeInUp" data-animation-out="animate-out fadeOut">
                           <span>{% trans %}MULTIPLATEFORME{% endtrans %}</span></h1>
                    </div>
                </div>
            </div>

        </div>

        <div class="hero_slider_left hero_slider_nav trans_200"><span class="trans_200">prec</span></div>
        <div class="hero_slider_right hero_slider_nav trans_200"><span class="trans_200">suiv</span></div>
    </div>
    <div class="hero_boxes">
        <div class="hero_boxes_inner">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 hero_box_col">
                    <a href="{{path('formations')}}" >
                        <div class="hero_box d-flex flex-row align-items-center justify-content-start">
                            <img src="images/earth-globe.svg" class="svg" alt="">
                            <div class="hero_box_content">
                                <h2 class="hero_box_title"> {% trans %}Gestion d'Entreprise{% endtrans %} </h2>
                            </div>
                        </div>
                    </a>
                    </div>

                    <div class="col-lg-4 hero_box_col">
                    <a href="{{path('formations')}}" >
                        <div class="hero_box d-flex flex-row align-items-center justify-content-start">
                            <img src="images/books.svg" class="svg" alt="">
                            <div class="hero_box_content">
                                <h2 class="hero_box_title"> {% trans %}Systèmes Informatiques {% endtrans %}</h2>
                                
                            </div>
                        </div>
                    </a>
                    </div>

                    <div class="col-lg-4 hero_box_col">
                    <a href="{{path('formations')}}" >
                        <div class="hero_box d-flex flex-row align-items-center justify-content-start">
                            <img src="images/professor.svg" class="svg" alt="">
                            <div class="hero_box_content">
                                <h2 class="hero_box_title">{% trans %}Formations et Assistances {% endtrans %}</h2>
                                
                            </div>
                        </div>
                    </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <!-- Popular -->
    <div class="popular page_section">
        <div class="container" id="solutions">
            <div class="row">
                <div class="col">
                    <div class="section_title text-center">
                        <h1>{% trans %}Nos solutions{% endtrans %}</h1>
                    </div>
                </div>
            </div>

            <div class="row course_boxes">

                <!-- Popular Course Item -->
                <div class="col-lg-4 course_box">
                    <div class="card">
                        <div class="card-img-container" style="background-image: url({{ asset('images/securit.jpeg') }})">
                            
                        </div>
                        <div class="card-body text-center">
                            <div class="card-title"><a href="#">E-SECURITY</a></div>
                            <div class="card-text">{% trans %}La gestion de votre entreprise de sécurité{% endtrans %}</div>
                        </div>
                        <div class="price_box d-flex flex-row align-items-center">
                            <div class="course_author_image">
                                <img src="{{ asset('images/app-web.jpg') }}">
                            </div>
                            <div class="course_author_name">APPLICATION <span>Web</span></div>
                            <div class="course_price d-flex flex-column align-items-center justify-content-center"><i class="fas fa-shopping-cart"></i></div>
                        </div>
                    </div>
                </div>

                <!-- Popular Course Item -->
                <div class="col-lg-4 course_box">
                    <div class="card">
                        <div class="card-img-container" style="background-image: url({{ asset('images/stock.jpg') }})">
                            
                        </div>

                        <div class="card-body text-center">
                            <div class="card-title"><a href="#">E-STOCK</a></div>
                            <div class="card-text">{% trans %}La gestion de stock dans tout son ensemble{% endtrans %}</div>
                        </div>
                        <div class="price_box d-flex flex-row align-items-center">
                            <div class="course_author_image">
                                <img src="{{ asset('images/app-web.jpg') }}" alt="">
                            </div>
                            <div class="course_author_name">APPLICATION <span>Web</span></div>
                            <div class="course_price d-flex flex-column align-items-center justify-content-center"><i class="fas fa-cart-plus"></i></div>
                        </div>
                    </div>
                </div>

                <!-- Popular Course Item -->
                <div class="col-lg-4 course_box">
                    <div class="card">
                        <div class="card-img-container" style="background-image: url({{ asset('images/beauty_sale.jpg') }})">
                            
                        </div>

                        <div class="card-body text-center">
                            <div class="card-title"><a href="#"> E-BEAUTY</a></div>
                            <div class="card-text"> {% trans %}Pour une bonne gestion de votre salon de beauté{% endtrans %}</div>
                        </div>
                        <div class="price_box d-flex flex-row align-items-center">
                            <div class="course_author_image">
                                <img src="{{ asset('images/app-web.jpg') }}" alt="">
                            </div>
                            <div class="course_author_name">APPLICATION <span>Web</span></div>
                            <div class="course_price d-flex flex-column align-items-center justify-content-center"><i class="fas fa-cart-arrow-down"></i></div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12 read-more-container">
                    <div class="button button_color_1 text-center trans_200"><a href="">{% trans %}Voir Plus{% endtrans %}</a></div>
                </div>

            </div>

        </div>

    </div>

    <!-- Enregistrer pas encore prete -->


    <!-- Services -->
    {{ include('components/services.html.twig') }}

    <!-- contact -->
    {{ include('components/register.html.twig') }}
    
    <!-- commentaires -->
    {{ include('components/commentaires.html.twig') }}
    
    <!-- A venir -->
    {{ include('components/prochain.html.twig') }}
    
    {% endblock %}
    {% block footer %}
    {{ include('components/footer.html.twig') }}
    {% endblock %}
{% endblock %}

templates/pages/boutique.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CAGESI Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('boutique/css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/elegant-icons.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/nice-select.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/jquery-ui.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/style.css')}}" type="text/css">
	
    
</head>

<body>

    {{ include('components/boutiqueHeader.html.twig') }}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>CAGESI Shop</h2>
                        <div class="breadcrumb__option">
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

	{{ include('components/boutiqueProduits.html.twig') }}

	{{ include('components/boutiqueSolutions.html.twig') }}
    <!-- footer -->
	 {{ include('components/boutiqueFooter.html.twig') }}
    

    <!-- Js Plugins -->
    <script src="{{asset('boutique/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{asset('boutique/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.nice-select.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery-ui.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.slicknav.js')}}"></script>
    <script src="{{asset('boutique/js/mixitup.min.js')}}"></script>
    <script src="{{asset('boutique/js/owl.carousel.min.js')}}"></script>
    <script src="{{asset('boutique/js/main.js')}}"></script>



</body>

</html>

templates/pages/commande.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CAGESI Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('boutique/css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/elegant-icons.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/nice-select.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/jquery-ui.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('boutique/css/style.css')}}" type="text/css">
	
    
</head>

<body>

    {{ include('components/boutiqueHeader.html.twig') }}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>CAGESI Shop</h2>
                        <div class="breadcrumb__option">
                            <span>Commande</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    {{ include('components/commandeFait.html.twig') }}
	
    <!-- footer -->
	{{ include('components/boutiqueFooter.html.twig') }}
    

    <!-- Js Plugins -->
    <script src="{{asset('boutique/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{asset('boutique/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.nice-select.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery-ui.min.js')}}"></script>
    <script src="{{asset('boutique/js/jquery.slicknav.js')}}"></script>
    <script src="{{asset('boutique/js/mixitup.min.js')}}"></script>
    <script src="{{asset('boutique/js/owl.carousel.min.js')}}"></script>
    <script src="{{asset('boutique/js/main.js')}}"></script>



</body>

</html>